### PR TITLE
Release latest contributions as 2.11 and EOL project

### PR DESCRIPTION
**Pull request by jangernert**
I didn't use `end-of-life-rebase` here because [`NewsFlash`](https://gitlab.com/news-flash/news_flash_gtk) is not a 1:1 rewrite but rather a re-imagination. Also it currently lacks integration for e.g. Nextcloud and TTRSS. So it would be completely useless to these users.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
i wouldn't EOL it directly and wait until the release is published first and then submit a merge request to EOL it form Flathub

**Comment by bilelmoussaoui** [comment]
Also you're supposed to use a flathub.json for that https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life :)

**Comment by jangernert** [comment]
Does EOL mean current users won't get this update any more? Otherwise I don't see a reason to do it in 2 steps.

**Comment by bilelmoussaoui** [comment]
> Does EOL mean current users won't get this update any more? Otherwise I don't see a reason to do it in 2 steps.

No it's not required at all. Never mind what I said before

**Comment by jangernert** [comment]
@bilelmoussaoui does that mean this PR is approved by you?
If so I would like to wait until NewsFlash is available on Flathub and then merge this.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui does that mean this PR is approved by you?
> If so I would like to wait until NewsFlash is available on Flathub and then merge this.

Looks good to me :) let me know if I can help with publishing NewsFlash on Flathub

**Comment by AsciiWolf** [comment]
I think that the repository should also be archived.

**Pull request merged**
